language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install paramiko
  - pip install requests
  - pip install openpyxl
  - pip install pymysql
  - pip install redis
  - pip install twine
  - pip install assertpy
  - pip install flask
  - pip install flask_restful
  - pip install jinja2
  - pip install pyaml
  - pip install deepdiff
  - pip install setuptools
  - pip install pymssql
  - pip install jsonschema
script:
  - # or py.test for Python versions 3.5 and below
  - python -m haf run -rc=1 -case=./testcases/test.xlsx,./testcases/test2.json,./testcases/test3.yml -rh=True -rod=./testcases/report.html -ld=./testcases
  - python -m haf run -rc=1 -case=./testcases/test2.json -rh=True -rod=./testcases/report.html -ld=./testcases
  - python -m haf run -rc=1 -case=./testcases/test3.yml -rh=True -rod=./testcases/report.html -ld=./testcases
  - python -m haf run -rc=2 -case=./testcases/test3.yml -rh=True -rod=./testcases/report.html -ld=./testcases
  - python -m haf run -rc=1 -case=./testcases/test.xlsx,./testcases/test2.json,./testcases/test3.yml -rh=True -rod=./testcases/report.html -ld=./testcases
  - python -m haf run -rc=3 -case=./testcases/test.xlsx,./testcases/test2.json,./testcases/test3.yml -rh=True -rod=./testcases/report1.html -ld=./testcases
  - cat ./testcases/report.html
  - cat ./testcases/report1.html