# encoding='utf-8'


BUS_PORT = 9000
BUS_DOMAIN = u"0.0.0.0"
BUS_AUTH_KEY = bytes("hafbus", encoding='utf-8')

CASE_TYPE_HTTPAPI = 0
CASE_TYPE_WEBUI = 1
CASE_TYPE_BASE = 2

MESSAGE_TYPE_CASE = 10
MESSAGE_TYPE_RESULT = 11
MESSAGE_TYPE_API_RESULT = 12
MESSAGE_TYPE_OTHER = 13